Add copyright and license headers to xopp2pdf script

diff --git a/xopp2pdf b/xopp2pdf
--- a/xopp2pdf
+++ b/xopp2pdf
@@ -1,3 +1,18 @@
-#!/bin/sh -ex
+#!/bin/sh
 
+# SPDX-FileCopyrightText: 2023 Luca Tagliavini <luca.tagliavini5@studio.unibo.it>
+# SPDX-FileCopyrightText: 2025 Eyad Issa <eyadlorenzo@gmail.com>
+#
+# SPDX-License-Identifier: AGPL-3.0-only
+
+set -e # Exit on error
+set -u # Treat unset variables as an error
+
+if [ "$#" -ne 1 ]; then
+  echo "This script converts a Xournal++ file to PDF."
+  echo "Usage: $0 <xopp_file.xopp>"
+  exit 1
+fi
+
+set -x # Print commands
 xournalpp -p "${1%.xopp}".pdf "$1"
